POST https://node-do-zero-4f1n.onrender.com/videos
Content-Type: application/json

{
    "title": "produção",
    "description": "This is a description of my first video.",
    "duration": 300
}

###
GET https://node-do-zero-4f1n.onrender.com/videos

###
PUT https://node-do-zero-4f1n.onrender.com/videos/d00f0d4a-d740-40f2-a445-dfbd77eb8a79
Content-Type: application/json

{
    "title": "My First Video3",
    "description": "This is a description of my first video.",
    "duration": 300
}

###
DELETE  https://node-do-zero-4f1n.onrender.com/videos/d00f0d4a-d740-40f2-a445-dfbd77eb8a79


